[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = false

# remappings
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

fs_permissions = [{ access = "read", path = "./broadcast" }]
solc = "0.8.20"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
zksync-local = "http://127.0.0.1:8011"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
